"""Initial migration

Revision ID: b278cabb61fc
Revises:
Create Date: 2026-08-08 04:36:42.464574

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b278cabb61fc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
